<?php
/**
* Copyright © Magento, Inc. All rights reserved.
* See COPYING.txt for license details.
*/
?>
<?php
// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis


/**
* Category view template
*
* @var $block \Magento\Framework\View\Element\Template
*/


?>

<!-- cria a div wrapper das logos de pagamentos -->
<div class="flags-cards-wrapper">
    <img src="<?php echo $block->getViewFileUrl('images/flags-cards-logos/amex.svg'); ?>" />
    <img src="<?php echo $block->getViewFileUrl('images/flags-cards-logos/master.svg'); ?>" />
    <img src="<?php echo $block->getViewFileUrl('images/flags-cards-logos/visa.svg'); ?>" />
    <img src="<?php echo $block->getViewFileUrl('images/flags-cards-logos/hipercard.svg'); ?>" />
    <img src="<?php echo $block->getViewFileUrl('images/flags-cards-logos/elo.svg'); ?>" />
    <img src="<?php echo $block->getViewFileUrl('images/flags-cards-logos/b-1.svg'); ?>" />
    <img src="<?php echo $block->getViewFileUrl('images/flags-cards-logos/paypal.svg'); ?>" />
    <img src="<?php echo $block->getViewFileUrl('images/flags-cards-logos/pix.svg'); ?>" />
    <img src="<?php echo $block->getViewFileUrl('images/flags-cards-logos/boleto.svg'); ?>" />
</div>
