<?php
/** @var \Magento\Catalog\Block\Product\ProductList\Toolbar $block */
?>

<?php if ($block->getTotalNum()): ?>
    <p class="toolbar-amount">
        <span class="toolbar-number">
            <?php if ($block->getTotalNum() == 1): ?>
                <?= $block->escapeHtml(__('1 produto encontrado')) ?>
            <?php else: ?>
                <?= $block->escapeHtml(
                    __(
                        '%1 produtos encontrados',
                        $block->getTotalNum()
                    )
                ) ?>
            <?php endif; ?>
        </span>
    </p>
<?php endif; ?>
